version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo "Package & Dependencies are getting installed"
      - npm install
      - echo "Packages have been installed"
      - echo "Storing Build Artifact to the Location"
artifacts:
  files:
    - '**/*'
