version: 0.2

phases:
  install:
    commands:
      - echo "Updating server"
      - sudo apt-get -y update
      - echo "Installing Node.js"
      - sudo apt install nodejs -y
      - sudo apt install npm -y
      - sudo npm install pm2@latest -g
      - echo "Node.js and npm have been installed"
      - node -v
      - npm -v
  build:
    commands:
      - echo "Package & Dependencies are getting installed"
      - npm install
      - echo "Packages have been installed"
      - echo "Storing Build Artifact to the Location"
artifacts:
  files:
    - '**/*'
